### ISSUE TITLE
Passing + to - (substract) causes error

### ISSUE THREAD

**Issue by NanoSector** [Archer70/desmond#7]
```PHP Fatal error:  Uncaught Error: Call to undefined method Desmond\functions\core\Add::value() in /Users/rkerkhof/Documents/Projects/Wild-IRC-Bot/vendor/archer70/desmond/src/functions/core/Subtract.php:24```

That error happens when you run this: `(- 5 5 5 + 9 9 9)` (found by Antes)

**Comment by Archer70** [comment]
Thanks for the bug report; we shouldn't be getting a fatal error from that! Just FYI, though, the correct form is `(- 5 5 5 (+ 5 5 5))`
